### PR TITLE
Installation screenshots and command line cheat sheet ready for styling

### PR DESCRIPTION
**Pull request by schmty**
This oddly won't let me submit a pull request for merging into the fall2013 branch..... Anyways. I have added the files install.php and gitcli.php to the site which both are working and have a respective navbar button. I have tested it in MAMP to make sure it all works. All that is left is that they need styling.

### CODE REVIEW

**Comment by schmty** [comment]
Wait, shouldn't this merge into fall2013?

**Comment by davidnuon** [comment]
You're right I goofed.

**Comment by schmty** [comment]
Should I just merge to fall2013? I can do that right?

**Comment by schmty** [comment]
Don't worry. Fixed it.

**Pull request merged**
